#!/bin/bash

names=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
ERROR_LOG="errors.txt"
API_URL="https://pokeapi.co/api/v2/pokemon/"
DICT="pokemon_data"
max_retries=3


> "$ERROR_LOG"

fetch_pokemon() {
    local name=$1
    local attempt=0

    while [ $attempt -le $max_retries ]; do
        if ! curl -fsSL "$API_URL/$name" -o "$DICT/$name.json"; then
            echo "[$(date)] ❌ Failed to fetch data for $name from $API_URL/$name" >> "$ERROR_LOG"
            attempt=$(($attempt + 1))
            sleep 1 
        else
            echo "Saved data to $DICT/$name.json ✅"
            return 0
        fi
    done

    echo "[$(date)] ❌ All attempts failed for $name" >> "$ERROR_LOG"
}

mkdir -p "$DICT"
for name in "${names[@]}"; do
    fetch_pokemon "$name" &
done

wait 
echo "All downloads complete ✅"

