#!/bin/bash

if [[ ! -f data.json ]]; then
  echo "Error: data.json not found!"
  exit 1
fi

name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
height=$(jq -r '.height' data.json)
weight=$(jq -r '.weight' data.json)
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

formatted_height=$(awk "BEGIN { printf \"%.1f\", $height / 10 }")
formatted_weight=$(awk "BEGIN { printf \"%.0f\", $weight / 10 }")

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
